### ISSUE TITLE
GStreamer: pipeline have not been created

### ISSUE THREAD

**Issue by jresch** [leswright1977/PySpectrometer#27]
Hello!

Great project! I am just having a bit of an issue with openCV and GStreamer. Any suggestions would be much appreciated

> [ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Failed to allocate required memory.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created

**Comment by leswright1977** [comment]
What OS are you using for this?

Les

**Comment by jresch** [comment]
Using Raspberry Pi 4 with Raspberry Pi OS (32 bit)  
https://www.raspberrypi.com/software/

**Comment by leswright1977** [comment]
That explains it. The Software was developed on Raspbian Buster (still
available) the latest Pi OS breaks the camera. At some point I will have to
recode a section of this, but I am on vacation just now.

Les

**Comment by jresch** [comment]
Well thank you so much for answering while you are on vacation!
I will give it a try it with Raspbian Buster.

**Comment by jresch** [comment]
Have you come across this warning before (this is using Raspbian Buster)

`[ WARN:0@1.005] global /tmp/pip-wheel-8c7uejek/opencv-python_88dbbad412c5416b992ae69de26299d6/opencv/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Traceback (most recent call last):
  File "pyspectrometer-v3.1.py", line 512, in <module>
    App(arg_parser().parse_args(), tkinter.Tk(), "PySpectrometer V3.0")
  File "pyspectrometer-v3.1.py", line 79, in __init__
    self.vid = MyVideoCapture(args.calibration or App.DEFAULT_CALIBRATION, self.video_source)
  File "pyspectrometer-v3.1.py", line 302, in __init__
    raise ValueError("Unable to open video source", video_source)
ValueError: ('Unable to open video source', 0)
`

**Comment by leswright1977** [comment]
Weird, is the picamera connected, verified and working?

Les

**Comment by jresch** [comment]
Yes, yes and yes.

**Comment by jresch** [comment]
As suggested online, I tried doing the cv2.VideoCapture(1) and cv2.VideoCapture(-1) and the cv2.VideoCapture(cv2.CAP_V4L2).
Didn't work

**Comment by jresch** [comment]
So....I switched out the camera and it worked with Raspbian Buster.

**Comment by Bra1nsen** [comment]
any updates?

**Comment by jresch** [comment]
For me at least, not on the newest OS.

**Comment by swagatk** [comment]
I got similar warning with my picamera when I used cv2.VideoCapture() to open it.  However, the following statement fixed these errors (Refer to this [link](https://raspberrypi.stackexchange.com/questions/111852/ubuntu-19-10-enabling-and-using-raspberry-pi-camera-module-v2-1/121790#121790?newreg=3f7562d0ce3b4753bcad4e86dd920a28) for original source):

```
import cv2
cap = cv2.VideoCapture(0, cv2.CAP_V4L) 
print(cap.isOpened())

```

I am using NoIR Camera V2 Raspberry Pi 4B with Raspbian Buster 32bit OS, opencv 4.5.5, python 2.7.16 as well as python 3.7.3. The option `cv2.CAP_V4L2` also works for me.

**Comment by bycmlla** [comment]
I have the same problem, 'pipeline have not been created' but i using the Jetson Nano Developer Kit and the imx219 camera. Someone knows help me?

**Comment by Petros626** [comment]
@swagatk for me your suggested method dont work. I'm using Bullseye 64-bit. @bycmlla I've read a lot of Issues and still struggle with the new RPi OS and the OV5647.

**Comment by swagatk** [comment]
> @swagatk for me your suggested method dont work. I'm using Bullseye 64-bit. @bycmlla I've read a lot of Issues and still struggle with the new RPi OS and the OV5647.

Hi, I have only tested this with Buster.

**Comment by Petros626** [comment]
**Update:** I figured out, that with two settings you can run a camera with _OpenCV_ (RPi or other manufacturer), **BUT** you very likely you will disable the new camera stack "libcamera".

Method 1: 
`sudo nano /boot/config.txt`
`#camera_auto_detect=1`
`gpu_mem=128` (minimum memory for camera)
`start_x=1` (enable the camera module)
`sudo reboot`

Method 2:
`sudo raspi-config`
Interface Options
Enable legay camera options

It's just a workaround and not a solution using cameras with the new Bullseye OS, but I think the guys from OpenCV will need just some time to fix that, so we aren't forced to use that.

**Comment by SocioPJ** [comment]
Tks @Petros626 !! It worked for me!!

**Comment by Aryansukhadia** [comment]
[ WARN:0@2.119] global ./modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Failed to allocate required memory.
[ WARN:0@2.119] global ./modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@2.119] global ./modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
Error: Unable to read from camera.

I tried all the methods discussed above but still getting this error. I am using Raspberrypi 5.

**Comment by Petros626** [comment]
I never worked with the Pi5, so I would just research through the web.
