### ISSUE TITLE
Newbie with problems running PySpectrometer

### ISSUE THREAD

**Issue by rtsandiego** [leswright1977/PySpectrometer#32]
Hello. I've just found your youtube channel Les. So many interesting videos. Inspired by your posts I've decided to try my hand at creating a Supercontinuum light source that you posted. I was going to buy a spectrometer but then noticed you have designed one using a Pi (but of course you have). I unfortunately am having trouble running the code. I'm somewhat a newbie on the Pi, so perhaps you might be able to see more easily what's wrong. 

_Here's my setup:_
Raspberry Pi 4 running: Debian GNU/Linux 12 (bookworm). 
Camera: Raspberry Pi HQ camera V1.0 - (I can run libcamera-hello with no issues except a warning about SDN tuning)
Display: PC Display: 4K display set to 2560 x 1440

_Here are my traceback errors:_
Traceback (most recent call last):
  File "/home/rosst2019/PySpectrometer2/src/./PySpectrometer2-Picam2-v1.0.py", line 261, in <module>
    intensity = savitzky_golay(intensity,17,savpoly)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rosst2019/PySpectrometer2/src/specFunctions.py", line 127, in savitzky_golay
    window_size = np.abs(np.int(window_size))
                         ^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.

---------------------Here's my command line info if you need to see it. 
rosst2019@raspberrypi:~/PySpectrometer2/src $ ./PySpectrometer2-Picam2-v1.0.py
[0:21:10.854209711] [3123]  INFO Camera camera_manager.cpp:284 libcamera v0.1.0+118-563cd78e
[0:21:10.901066323] [3129]  WARN RPiSdn sdn.cpp:39 Using legacy SDN tuning - please consider moving SDN inside rpi.denoise
[0:21:10.903741029] [3129]  INFO RPI vc4.cpp:444 Registered camera /base/soc/i2c0mux/i2c@1/imx477@1a to Unicam device /dev/media4 and ISP device /dev/media2
[0:21:10.903831676] [3129]  INFO RPI pipeline_base.cpp:1142 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
[0:21:10.910147872] [3123]  INFO Camera camera_manager.cpp:284 libcamera v0.1.0+118-563cd78e
[0:21:10.954305816] [3132]  WARN RPiSdn sdn.cpp:39 Using legacy SDN tuning - please consider moving SDN inside rpi.denoise
[0:21:10.956771543] [3132]  INFO RPI vc4.cpp:444 Registered camera /base/soc/i2c0mux/i2c@1/imx477@1a to Unicam device /dev/media4 and ISP device /dev/media2
[0:21:10.956853894] [3132]  INFO RPI pipeline_base.cpp:1142 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
[0:21:10.963521455] [3123]  INFO Camera camera.cpp:1183 configuring streams: (0) 800x600-RGB888 (1) 2028x1520-SBGGR12_CSI2P
[0:21:10.964081226] [3132]  INFO RPI vc4.cpp:608 Sensor: /base/soc/i2c0mux/i2c@1/imx477@1a - Selected sensor format: 2028x1520-SBGGR12_1X12 - Selected unicam format: 2028x1520-pBCC
Loading calibration data...
Loading of Calibration data failed (missing caldata.txt or corrupted data!
Loading placeholder data...
You MUST perform a Calibration to use this software!

Calculating second order polynomial...
           2
3.125e-05 x + 0.4375 x + 380
Generating Wavelength Data!

Done! Note that calibration with only 3 wavelengths will not be accurate!
Traceback (most recent call last):
  File "/home/rosst2019/PySpectrometer2/src/./PySpectrometer2-Picam2-v1.0.py", line 261, in <module>
    intensity = savitzky_golay(intensity,17,savpoly)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rosst2019/PySpectrometer2/src/specFunctions.py", line 127, in savitzky_golay
    window_size = np.abs(np.int(window_size))
                         ^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?

**Comment by rtsandiego** [comment]
Ok, thank you. It is running now. My first steps into the Supercontinuum project...
